#!/bin/sh

TARGET=simpyx
USER=simpy
LIB=simpy
VERSION=3.0.2
NAME=$LIB-$VERSION
URL=https://bitbucket.org/simpy/$LIB/get/$VERSION.tar.gz

wget -O $NAME.tar.gz $URL
tar xvfz $NAME.tar.gz
DIR=$(tar -tf simpy-3.0.2.tar.gz | head -1 | cut -d/ -f1)
rm -f $NAME.tar.gz
mv $DIR/$LIB simpyx/$LIB
rm -R -f $DIR
