#!/bin/sh

TARGET=simpyx
USER=simpy
LIB=simpy
VERSION=3.0.2
NAME=$LIB-$VERSION
URL=https://bitbucket.org/$USER/$LIB/get/$VERSION.tar.gz

wget -O $NAME.tar.gz $URL
tar xvfz $NAME.tar.gz
DIR=$(tar -tf $NAME.tar.gz | head -1 | cut -d/ -f1)
rm -f $NAME.tar.gz
mv -f $DIR/$LIB/* $TARGET/
rm -R -f $DIR
